version: '3'

services:
  pokedex-db: 
    image: mongo:5.0.0
    container_name: pokedex-mongodb
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: nest-pokedex
    volumes:
      - ./mongo:/data/db